language: node_js
node_js:
- '10'
install: true
script: npm test
deploy:
  provider: npm
  email: 949582269@qq.com
  api_key:
    secure: TP6rcPxpJIRfvzChqCOb3YW8VSGZmwZItzKj/4xCjTmK1k4OPXLKo3RyYg53ErA7MzW83DHjqX4NE6BerNDswIzYpvzenL5MM0QCAOvwCo6bwO1ZB9vGV1CuQ0VrBwXQEtmMum5F+3/Im0+a92iUOEh5hRSOFucv4KR7EJDzVF9S5kTc0D4UevivQz/ROCZ36QWpdhO9BQQ0nLALiu3Bms81vtDiFELBbNTyGdgQzNEqScyzadbLfoMvWPVe6W3eSOjT+BcKqhiCL6GnptkybRJLuv18AwBBCHveA7f3FbIMRvnWxMy0EBrBojwI2RaNp6C5hz9mHV1dGCr5xzCQW4g72rY0MAGUsSEGCPDMFtsay2G9yQ0dUqG2m0QgcGQBo5RZ9GNvgIyzhhlijp6yADNezHqQEg0IZtTBYHbZAUxtpc8ALam6qPVGqg58W43g3QRIizdLfVtP/BaHwvacdAyfnim/O0RuZ+FFYL51GoiQN0jEQviWTLjylDvsKjERouyV5NvpYpAFlviMLhH0vBADIrIX/Vh7vwolf7cxJYP95JHXzmKKOhiy/hcF2rjx3VVEQklNOJQGwpSnzTX2uFzIQHTmJ//IVgau5uWoJZnBa+5dZlUgu47n6zjWFGSfcIGssBDeute9WXpvwB6I3/FOYOU/lTpiMvMnH+lDEk8=
  on:
    tags: true
    repo: dkvirus/tein
  tag: latest
